// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfy7te8bRZXd9TjQShYprHicT8EInk7WU',
    appId: '1:285803966525:web:43ec68293fdf9f215cfa54',
    messagingSenderId: '285803966525',
    projectId: 'myconnect-56a88',
    authDomain: 'myconnect-56a88.firebaseapp.com',
    storageBucket: 'myconnect-56a88.firebasestorage.app',
    measurementId: 'G-V0JGVQ5X0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVGEa0m1TPsmpn1ruRxcqrINekXcqQZIM',
    appId: '1:285803966525:android:fced5398ad4d00e95cfa54',
    messagingSenderId: '285803966525',
    projectId: 'myconnect-56a88',
    storageBucket: 'myconnect-56a88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuuqxDPZHaZWqYQf3JrAi8gZDa8i2FNy8',
    appId: '1:285803966525:ios:d0f2fc4aea6c27635cfa54',
    messagingSenderId: '285803966525',
    projectId: 'myconnect-56a88',
    storageBucket: 'myconnect-56a88.firebasestorage.app',
    iosBundleId: 'com.octosoft.myconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuuqxDPZHaZWqYQf3JrAi8gZDa8i2FNy8',
    appId: '1:285803966525:ios:d0f2fc4aea6c27635cfa54',
    messagingSenderId: '285803966525',
    projectId: 'myconnect-56a88',
    storageBucket: 'myconnect-56a88.firebasestorage.app',
    iosBundleId: 'com.octosoft.myconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfy7te8bRZXd9TjQShYprHicT8EInk7WU',
    appId: '1:285803966525:web:9e5d07f6d5a7af9a5cfa54',
    messagingSenderId: '285803966525',
    projectId: 'myconnect-56a88',
    authDomain: 'myconnect-56a88.firebaseapp.com',
    storageBucket: 'myconnect-56a88.firebasestorage.app',
    measurementId: 'G-TDCWEPWXWW',
  );
}
